<?php

namespace app\api\controller;

use think\App;
use think\Controller;
use think\Db;

class Base extends Controller
{
    protected $user;
    protected $middleware = ['check'];

    function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $token = $this->request->header('token');
        $this->user = Db::name('user')->where('token',$token)->find();
        
    }


}